// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"ch01-robot-that-doubts.mdx": () => import("../content/chapters/ch01-robot-that-doubts.mdx?collection=docs"), "ch02-probability.mdx": () => import("../content/chapters/ch02-probability.mdx?collection=docs"), "ch03-geometry-of-motion.mdx": () => import("../content/chapters/ch03-geometry-of-motion.mdx?collection=docs"), "ch04-rusty-and-sensors.mdx": () => import("../content/chapters/ch04-rusty-and-sensors.mdx?collection=docs"), "ch05-bayes-filter.mdx": () => import("../content/chapters/ch05-bayes-filter.mdx?collection=docs"), "ch06-kalman-filters.mdx": () => import("../content/chapters/ch06-kalman-filters.mdx?collection=docs"), "ch07-ekf-ukf-manifolds.mdx": () => import("../content/chapters/ch07-ekf-ukf-manifolds.mdx?collection=docs"), "ch08-nonparametric-filters.mdx": () => import("../content/chapters/ch08-nonparametric-filters.mdx?collection=docs"), "ch09-motion-models.mdx": () => import("../content/chapters/ch09-motion-models.mdx?collection=docs"), "ch10-sensor-models.mdx": () => import("../content/chapters/ch10-sensor-models.mdx?collection=docs"), "ch11-localization-gaussian.mdx": () => import("../content/chapters/ch11-localization-gaussian.mdx?collection=docs"), "ch12-localization-global.mdx": () => import("../content/chapters/ch12-localization-global.mdx?collection=docs"), "ch13-occupancy-grids.mdx": () => import("../content/chapters/ch13-occupancy-grids.mdx?collection=docs"), "ch14-ekf-slam.mdx": () => import("../content/chapters/ch14-ekf-slam.mdx?collection=docs"), "ch15-factor-graphs.mdx": () => import("../content/chapters/ch15-factor-graphs.mdx?collection=docs"), "ch16-scan-matching.mdx": () => import("../content/chapters/ch16-scan-matching.mdx?collection=docs"), "ch17-fastslam.mdx": () => import("../content/chapters/ch17-fastslam.mdx?collection=docs"), "ch18-visual-slam.mdx": () => import("../content/chapters/ch18-visual-slam.mdx?collection=docs"), "ch19-map-representations.mdx": () => import("../content/chapters/ch19-map-representations.mdx?collection=docs"), "ch20-motion-planning.mdx": () => import("../content/chapters/ch20-motion-planning.mdx?collection=docs"), "ch21-mdps.mdx": () => import("../content/chapters/ch21-mdps.mdx?collection=docs"), "ch22-pomdps.mdx": () => import("../content/chapters/ch22-pomdps.mdx?collection=docs"), "ch23-mppi.mdx": () => import("../content/chapters/ch23-mppi.mdx?collection=docs"), "ch24-exploration.mdx": () => import("../content/chapters/ch24-exploration.mdx?collection=docs"), "ch25-learning.mdx": () => import("../content/chapters/ch25-learning.mdx?collection=docs"), "ch26-capstone.mdx": () => import("../content/chapters/ch26-capstone.mdx?collection=docs"), "index.mdx": () => import("../content/chapters/index.mdx?collection=docs"), }),
};
export default browserCollections;